name: "evmqtt"
description: "Linux input event to MQTT gateway for Home Assistant with auto-discovery"
version: "1.1.0"
slug: "evmqtt"
url: "https://github.com/odtgit/evmqtt"
arch:
  - amd64
  - aarch64
startup: "system"
init: false
host_network: true
privileged:
  - SYS_RAWIO
full_access: true
options:
  mqtt_host: "homeassistant.local"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_tls: false
  mqtt_tls_ca: ""
  name: "Input Events"
  topic: "homeassistant/sensor/evmqtt"
  auto_discover: true
  filter_keys_only: true
  keystates: ["PRESS"]
  devices: []
  enabled_devices: []
  log_level: "info"
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  mqtt_tls: bool
  mqtt_tls_ca: str?
  name: str
  topic: str
  auto_discover: bool
  filter_keys_only: bool
  keystates:
    - "list(PRESS|RELEASE|REPEAT)"
  devices:
    - str?
  enabled_devices:
    - str?
  log_level: list(debug|info|warning|error)
panel_icon: "mdi:remote"
panel_title: "evmqtt"
