services:
  evmqtt:
    hostname: evmqtt
    container_name: evmqtt
    build:
      context: .
      args:
        BUILD_FROM: python:3.12-alpine3.18
    image: odtdock/evmqtt:latest
    restart: always
    volumes:
      - ./config.json:/data/config.json
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TZ=Europe/Stockholm"
    devices:
      - /dev/input/event4
    network_mode: host
